apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-server
  labels:
    app: test-web
  annotations:
    kubernetes.io/change-cause: web-portal-docker:1.0.10
  namespace: test
spec:
  progressDeadlineSeconds: 120
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      name: tomcat-server
      labels:
        app: test-web
    spec:
      containers:
        - name: tomcat-server
          image: seoulbigdata-registry.ncr.gov-ntruss.com/web-portal-docker:1.0.10
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 300Mi
          livenessProbe:
            exec:
              command: ["cat", "/prod/web-portal/ready.txt"]
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /
              port: 8080
