apiVersion: v1
kind: Service
metadata:
  name: test-server-service
  labels:
    app: test
  namespace: test
spec:
  type: NodePort
  selector:
    app: test-web
    color: blue
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30088
