apiVersion: v1
kind: Service
metadata:
  name: test-server-service
  labels:
    app: test
  namespace: test
spec:
  type: NodePort
  selector:
    app: test-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
