apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-mtv-deployment
  labels:
    app: test-mtv
  annotations:
    kubernetes.io/change-cause: seoulbigdata-registry.ncr.gov-ntruss.com/mtv-dotnet-docker:0.0.1
  namespace: mtv-dotnet
spec:
  replicas: 3
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: test-mtv
  template:
    metadata:
      labels:
        app: test-mtv
    spec:
      containers:
        - name: test-mtv
          image: seoulbigdata-registry.ncr.gov-ntruss.com/mtv-dotnet-docker:0.0.1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 10m
              memory: 300Mi
          livenessProbe:
            initialDelaySeconds: 90
            periodSeconds: 10
            httpGet:
              path: /bsp/mtv
              port: 5000
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /bsp/mtv
              port: 5000
