apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /bsp/mtv
  name: test-mtv-svc
  labels:
    app: test-mtv
  namespace: mtv-dotnet
spec:
  type: NodePort
  selector:
    app: test-mtv
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30089
